---
name: Ansible Molecule

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
        working-directory: "${{ github.repository }}"

      - name: list directory
        run: ls -al
        working-directory: "${{ github.repository }}"

      - name: Test with molecule
        run: molecule test
        working-directory: "${{ github.repository }}"
